import "../styles/globals.css";

//theme
import "primereact/resources/themes/arya-blue/theme.css";

//core
import "primereact/resources/primereact.min.css";

export const metadata = {
  title: "IDoCode",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-full w-full">{children}</div>
      </body>
    </html>
  );
}
